name: picksy
description: "An app to generate random things like names, numbers, colors, and more."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # UI / State
  provider: ^6.1.2

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # IAP
  in_app_purchase: ^3.2.3

  # Links (Buy me a coffee, GitHub issues, etc.)
  url_launcher: ^6.3.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
